import struct
import os
import zlib

def main():
    file_path = "output.bin"
    
    if not os.path.exists(file_path):
        print(f"Failed to open {file_path} for reading.")
        return

    # Constants matching EventHandle configuration
    max_string_size = 64
    string_buffer_size = max_string_size + 1  # 65 bytes
    
    # EventLedgerEntry struct format:
    # 4x uint64_t (Q) + 1x uint32_t (I)
    # + 4 bytes padding (4x) due to C++ standard struct alignment
    # '<' ensures little-endian parsing which is standard for x86/ARM memory dumps
    struct_format = '<QQQQI4x'
    struct_size = struct.calcsize(struct_format) # 40 bytes
    
    # Total fixed record size = 65 + 40 = 105 bytes
    fixed_record_size = string_buffer_size + struct_size 
    
    actual_counts = {}
    
    print("\nReading back data from output.bin:")
    
    with open(file_path, "rb") as f:
        crc_data = f.read(4)
        if not crc_data or len(crc_data) < 4:
            print("File too small to contain CRC header.")
            return
            
        expected_crc = struct.unpack('<I', crc_data)[0]
        payload_data = f.read()
        actual_crc = zlib.crc32(payload_data) & 0xFFFFFFFF
        
        if expected_crc != actual_crc:
            print(f" [FAIL] CRC mismatch! Expected {hex(expected_crc)}, got {hex(actual_crc)}")
            return
            
        print(f" [SUCCESS] CRC Match: {hex(expected_crc)}\n")

        record_idx = 1
        offset = 0
        
        while offset + fixed_record_size <= len(payload_data):
            chunk = payload_data[offset:offset+fixed_record_size]
            offset += fixed_record_size
                
            # 1. Deserialize the string
            raw_string = chunk[:string_buffer_size]
            # Split at the first null byte '\0' and decode to utf-8
            event_str = raw_string.split(b'\0', 1)[0].decode('utf-8', errors='ignore')
            
            # 2. Deserialize the EventLedgerEntry struct
            raw_struct = chunk[string_buffer_size:string_buffer_size + struct_size]
            first_mono, last_mono, first_wall, last_wall, count = struct.unpack(struct_format, raw_struct)
            
            # Skip zero-padded trailing empty records generated by fixed-size buffer padding
            if not event_str and count == 0:
                continue
                
            # Store in our dictionary for later comparison
            actual_counts[event_str] = count
            
            print(f"--- Record #{record_idx} ---")
            print(f"Event Message : {event_str}")
            print(f"Occurrences   : {count}")
            print(f"First Mono TS : {first_mono}")
            print(f"Last Mono TS  : {last_mono}")
            print(f"First Wall TS : {first_wall}")
            print(f"Last Wall TS  : {last_wall}\n")
            
            record_idx += 1
            
    # Verify the parsed data exactly matches our expected deterministic inputs
    expected_counts = {
        "Application started": 1,
        "Avg FPS not reached": 10,
        "FrameDroped": 15,
        "Odometery Error": 5,
        "Shared Thread Event": 60
    }
    
    print("------------------------------------------")
    print("Validating decoded data...")
    test_passed = True
    
    for expected_str, expected_count in expected_counts.items():
        if expected_str not in actual_counts:
            print(f" [FAIL] Missing expected event: '{expected_str}'")
            test_passed = False
        elif actual_counts[expected_str] != expected_count:
            print(f" [FAIL] Count mismatch for '{expected_str}'. Expected {expected_count}, got {actual_counts[expected_str]}")
            test_passed = False
            
    if test_passed and len(actual_counts) == len(expected_counts):
        print(" [SUCCESS] ALL TESTS PASSED! Decoded data perfectly matches logged data.")
    elif len(actual_counts) != len(expected_counts):
        print(" [FAIL] Unexpected events found in decoded payload.")

if __name__ == "__main__":
    main()
