#include "EventVault.hpp"
#include <iostream>
#include <fstream>
#include <thread>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <unordered_map>
#include <vector>
#include <iomanip>

// Forward declaration for the transporter interface.
// The actual implementation should be provided by the user.
struct AraTransporter final : public evt::ITransporter
{
    void publish(const uint8_t* data, const size_t size) override
    {
        std::cout << "Writing Data to output.bin\n";
        std::ofstream l_file("output.bin", std::ios::binary | std::ios::trunc);
        if (l_file.is_open())
        {
            l_file.write(reinterpret_cast<const char*>(data), size);
        }
    }
};

int main()
{
    // Clear the file from previous runs to ensure a clean slate
    std::remove("output.bin");

    // Example usage:
    evt::EventHandle l_handle{};
    l_handle.m_lockFreeQueueSize = 1024U;
    l_handle.m_maxLedgerEntries = 256U;
    l_handle.m_maxStringSize = 64U;
    l_handle.m_sleepDurationMs = 10U;
    l_handle.m_ringSize = 150U;
    l_handle.m_transporter = std::make_unique<AraTransporter>();

    const auto l_ret = evt::EventVault::init(std::move(l_handle));

    if(l_ret != evt::ErrorType::SUCCESS)
    {
        std::cout<<"Init Err : "<<(int)l_ret<<std::endl;
    }

    const auto l_ret2 = evt::EventVault::recordEvent("Application started");

    if(l_ret2 != evt::ErrorType::SUCCESS)
    {
        std::cout<<"Record Err : "<<(int)l_ret2<<std::endl;
    }

    std::cout << "Logging known deterministic events concurrently via threads...\n";

    const auto threadFunc1 = []() {
        for (int i = 0; i < 10; ++i) evt::EventVault::recordEvent("Avg FPS not reached");
        for (int i = 0; i < 20; ++i) {
            evt::EventVault::recordEvent("Shared Thread Event");
        }
    };

    const auto threadFunc2 = []() {
        for (int i = 0; i < 15; ++i) evt::EventVault::recordEvent("FrameDroped");
        for (int i = 0; i < 20; ++i) {
            evt::EventVault::recordEvent("Shared Thread Event");
        }
    };

    const auto threadFunc3 = []() {
        for (int i = 0; i < 5; ++i) evt::EventVault::recordEvent("Odometery Error");
        for (int i = 0; i < 20; ++i) {
            evt::EventVault::recordEvent("Shared Thread Event");
        }
    };

    std::thread t1(threadFunc1);
    std::thread t2(threadFunc2);
    std::thread t3(threadFunc3);

    t1.join();
    t2.join();
    t3.join();

    std::cout << "All work Completed \n";

    // Ensure everything is flushed out to output.bin before reading
    evt::EventVault::deInit();

    std::cout << "\nReading back data from output.bin:\n";
    std::ifstream l_file("output.bin", std::ios::binary | std::ios::ate);
    if (l_file.is_open())
    {
        // Determine the total file size
        const size_t l_fileSize = static_cast<size_t>(l_file.tellg());
        l_file.seekg(0, std::ios::beg);

        // Read the entire serialized payload into a buffer at once
        std::vector<uint8_t> l_readBuffer(l_fileSize);
        if (l_file.read(reinterpret_cast<char*>(l_readBuffer.data()), l_fileSize))
        {
            if (l_fileSize < sizeof(uint32_t))
            {
                std::cout << "File too small to contain CRC header.\n";
                return -1;
            }

            uint32_t l_expectedCrc{};
            std::memcpy(&l_expectedCrc, l_readBuffer.data(), sizeof(uint32_t));
            uint32_t l_actualCrc = evt::calculateCRC32(l_readBuffer.data() + sizeof(uint32_t), l_fileSize - sizeof(uint32_t));

            if (l_expectedCrc != l_actualCrc)
            {
                std::cout << " [FAIL] CRC mismatch! Expected 0x" << std::hex << l_expectedCrc 
                          << ", got 0x" << l_actualCrc << std::dec << "\n";
                return -1;
            }
            std::cout << " [SUCCESS] CRC Match: 0x" << std::hex << l_expectedCrc << std::dec << "\n\n";

            const size_t l_fixedRecordSize = l_handle.m_maxStringSize + 1 + sizeof(evt::EventLedgerEntry);
            size_t l_offset = sizeof(uint32_t);
            int l_recordIdx = 1;

            // Store parsed results for automated verification
            std::unordered_map<std::string, uint32_t> l_actualCounts;

            // Stride through the buffer deserializing each fixed-length record
            while (l_offset + l_fixedRecordSize <= l_fileSize)
            {
                // 1. Deserialize the string
                std::string l_eventStr(reinterpret_cast<const char*>(l_readBuffer.data() + l_offset));
                l_offset += l_handle.m_maxStringSize + 1;

                // 2. Deserialize the EventLedgerEntry struct
                evt::EventLedgerEntry l_entry{};
                std::memcpy(&l_entry, l_readBuffer.data() + l_offset, sizeof(evt::EventLedgerEntry));
                l_offset += sizeof(evt::EventLedgerEntry);

                // Skip zero-padded trailing empty records generated by fixed-size buffer padding
                if (l_eventStr.empty() && l_entry.m_count == 0)
                {
                    continue;
                }

                // Store in our map for later comparison
                l_actualCounts[l_eventStr] = l_entry.m_count;

                std::cout << "--- Record #" << l_recordIdx++ << " ---\n"
                          << "Event Message : " << l_eventStr << "\n"
                          << "Occurrences   : " << l_entry.m_count << "\n"
                          << "First Mono TS : " << l_entry.m_firstMonoTS << "\n"
                          << "Last Mono TS  : " << l_entry.m_lastMonoTS << "\n"
                          << "First Wall TS : " << l_entry.m_firstWallTS << "\n"
                          << "Last Wall TS  : " << l_entry.m_lastWallTS << "\n\n";
            }

            // Verify the parsed data exactly matches our expected deterministic inputs
        const std::unordered_map<std::string, uint32_t> l_expectedCounts = {
                {"Application started", 1},
                {"Avg FPS not reached", 10},
                {"FrameDroped", 15},
                {"Odometery Error", 5},
                {"Shared Thread Event", 60}
            };

            std::cout << "------------------------------------------\n";
            std::cout << "Validating decoded data...\n";
            bool l_testPassed = true;

            for (const auto& [expectedStr, expectedCount] : l_expectedCounts)
            {
                auto it = l_actualCounts.find(expectedStr);
                if (it == l_actualCounts.end())
                {
                    std::cout << " [FAIL] Missing expected event: '" << expectedStr << "'\n";
                    l_testPassed = false;
                }
                else if (it->second != expectedCount)
                {
                    std::cout << " [FAIL] Count mismatch for '" << expectedStr 
                              << "'. Expected " << expectedCount << ", got " << it->second << "\n";
                    l_testPassed = false;
                }
            }

            if (l_testPassed && l_actualCounts.size() == l_expectedCounts.size())
            {
                std::cout << " [SUCCESS] ALL TESTS PASSED! Decoded data perfectly matches logged data.\n";
            }
            else if (l_actualCounts.size() != l_expectedCounts.size())
            {
                std::cout << " [FAIL] Unexpected events found in decoded payload.\n";
            }
        }
        else
        {
            std::cout << "Failed to read the complete serialized file.\n";
        }
        l_file.close();
    }
    else
    {
        std::cout << "Failed to open output.bin for reading.\n";
    }

    return 0;
}