#include "EventVault.hpp"
#include <iostream>
#include <fstream>
#include <thread>
#include <chrono>
#include <cstdio>
#include <random>
#include <atomic>
// Forward declaration for the transporter interface.
// The actual implementation should be provided by the user.
struct AraTransporter final : public evt::ITransporter
{
    virtual void publish(const uint8_t* data, size_t size)
    {
        printf("Writing Data to output.bin\n");
        std::ofstream l_file("output.bin", std::ios::binary | std::ios::trunc);
        if (l_file.is_open())
        {
            l_file.write(reinterpret_cast<const char*>(data), size);
        }
    }
};
int main()
{
    // Clear the file from previous runs to ensure a clean slate
    std::remove("output.bin");

    // Example usage:
    evt::EventHandle handle{};
    handle.m_transporter = std::make_unique<AraTransporter>();
    handle.m_ringSize = 50;
    auto l_ret = evt::EventVault::init(std::move(handle));

    if(l_ret != evt::ErrorType::SUCCESS)
    {
        std::cout<<"Init Err : "<<(int)l_ret<<std::endl;
    }

    auto l_ret2 = evt::EventVault::recordEvent("Application started");
    if(l_ret2 != evt::ErrorType::SUCCESS)
    {
        std::cout<<"Record Err : "<<(int)l_ret2<<std::endl;
    }

    std::atomic<bool> l_active{true};

    // Thread 1: Random Odometry Errors
    std::thread l_odomThread([&l_active]() {
        std::random_device rd;
        std::mt19937 gen(rd());
        std::uniform_int_distribution<> dist(0, 2);
        std::uniform_int_distribution<> sleepDist(1, 10);
        const char* events[] = {"Odom Err", "Odom Err 116", "Odom Err 255"};
        
        while (l_active) {
            evt::EventVault::recordEvent(events[dist(gen)]);
            std::this_thread::sleep_for(std::chrono::milliseconds(sleepDist(gen)));
        }
    });

    // Thread 2: Random Frame Drop Errors
    std::thread l_frameThread([&l_active]() {
        std::random_device rd;
        std::mt19937 gen(rd());
        std::uniform_int_distribution<> dist(0, 3);
        std::uniform_int_distribution<> sleepDist(1, 10);
        const char* events[] = {"FrameDrop for ML", "FrameDrop for MR", "FrameDrop for RV", "FrameDrop for FV"};
        
        while (l_active) {
            evt::EventVault::recordEvent(events[dist(gen)]);
            std::this_thread::sleep_for(std::chrono::milliseconds(sleepDist(gen)));
        }
    });

    // Let the multi-threaded producers generate events for 1 second
    std::this_thread::sleep_for(std::chrono::seconds(1));
    l_active = false;

    // Wait for producers to exit gracefully
    l_odomThread.join();
    l_frameThread.join();
    
    // Ensure everything is flushed out to output.bin before reading
    evt::EventVault::deInit();

    std::cout << "\nReading back data from output.bin:\n";
    FILE* l_file = std::fopen("output.bin", "rb");
    if (l_file)
    {
        int l_recordIdx = 1;
        while (true)
        {
            std::vector<char> l_strBuf(handle.m_maxStringSize + 1, 0);
            if (std::fread(l_strBuf.data(), 1, l_strBuf.size(), l_file) != l_strBuf.size())
            {
                break; // End of file
            }
            std::string l_eventStr(l_strBuf.data());

            evt::EventLedgerEntry l_entry{};
            if (std::fread(&l_entry, sizeof(evt::EventLedgerEntry), 1, l_file) != 1)
            {
                break;
            }

            // Skip zero-padded trailing empty records generated by fixed-size buffer padding
            if (l_eventStr.empty() && l_entry.m_count == 0)
            {
                continue;
            }

            std::cout << "--- Record #" << l_recordIdx++ << " ---\n"
                      << "Event Message : " << l_eventStr << "\n"
                      << "Occurrences   : " << l_entry.m_count << "\n"
                      << "First Mono TS : " << l_entry.m_firstMonoTS << "\n"
                      << "Last Mono TS  : " << l_entry.m_lastMonoTS << "\n"
                      << "First Wall TS : " << l_entry.m_firstWallTS << "\n"
                      << "Last Wall TS  : " << l_entry.m_lastWallTS << "\n\n";
        }
        std::fclose(l_file);
    }
    else
    {
        std::cout << "Failed to open output.bin for reading.\n";
    }

    return 0;
}